version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7

jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6-jessie
    environment:
      - VCR_RECORD_MODE=none
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install mkvtoolnix
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            wget -q -O - https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt | sudo apt-key add -
            echo "deb https://mkvtoolnix.download/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/mkvtoolnix.download.list
            sudo apt-get update
            sudo apt-get -t jessie install mkvtoolnix
      - restore_cache:
          keys:
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e 'git+git@github.com:Flexget/Flexget.git#egg=flexget[dev]'
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie